### ISSUE TITLE
Replacement of Nginx with Apache

### ISSUE THREAD

**Issue by thepapanoob** [dps/piui#2]
does PIUI rely on some features of nginx? or can i easily replace nginx with apache?
Greetz Kru

**Comment by dps** [comment]
nginx is used to force an HTTP/1.0 connection to the cherrypy backend.  Apache is a web server rather than a reverse proxy like nginx, so you could try to replace cherrypy with apache + mod_python or similar, but this would require quite a lot of work - the hanging GETs which PiUi uses to make the browser <--> device interaction event driven rely on the internals of cherrypy.
